<?php
/**
 * Created by PhpStorm.
 * User: ddiallo
 * Date: 9/13/19
 * Time: 12:50 PM
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implement hook_form_FORM_ID_alter
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */

function validation_rules_entryform_form_node_tajikistan_data_entry_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'validation_rules_entryform/validation-rules';
}

function validation_rules_entryform_form_node_tajikistan_data_entry_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'validation_rules_entryform/show-validation-messages';
}